name: my_vpn_app
description: A VLESS VPN client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"  # Поднимаем минимальную версию

dependencies:
  flutter:
    sdk: flutter
  flutter_vless: ^1.0.3  # Только основная библиотека
  # flutter_vless_android_emulator: ^1.0.1  # Временно отключаем

flutter:
  uses-material-design: true
